# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 05:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20160330_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='english_name',
            field=models.CharField(default=datetime.datetime(2016, 4, 6, 5, 28, 8, 544000, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='portrait',
            field=models.ImageField(default='touxiang.jpg', upload_to='img/'),
        ),
    ]
